parameters:
    apache_tika:
        config:
            tika_path: %apache_tika.config.tika_path%
            tika_host: %apache_tika.config.tika_host%
            tika_port: %apache_tika.config.tika_port%
