notifications:
  email: false

language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

env:
    global:
        - deps=high

before_script:
    - \[ -f $HOME/build/jolicode/ApacheTikaBundle/Tests/bin/tika-app.jar \] || wget -O $HOME/build/jolicode/ApacheTikaBundle/Tests/bin/tika-app.jar http://apache.mirrors.ovh.net/ftp.apache.org/dist/tika/tika-app-1.11.jar
    - \[ -f $HOME/build/jolicode/ApacheTikaBundle/Tests/bin/tika-server.jar \] || wget -O $HOME/build/jolicode/ApacheTikaBundle/Tests/bin/tika-server.jar -nc http://apache.mirrors.ovh.net/ftp.apache.org/dist/tika/tika-server-1.11.jar
    - java -jar $HOME/build/jolicode/ApacheTikaBundle/Tests/bin/tika-server.jar &
    - sleep 5

matrix:
    include:
        - php: hhvm
        - php: 5.4
        - php: 5.5
        - php: 5.6
          env: deps=high
        - php: 7.0
          env: deps=low

install:
    - if [ "$deps" = "low" ]; then composer --prefer-source --prefer-lowest update; fi;
    - if [ "$deps" != "low" ]; then composer --prefer-source update; fi;

script:
    - make travis_test
